In [91]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [92]:
from sklearn import preprocessing
from sklearn.preprocessing import OrdinalEncoder,LabelBinarizer

In [93]:
df = pd.read_csv('mushrooms.csv')

In [95]:
df = df[['class', 'cap-surface', 'bruises', 'odor', 'population']]

In [96]:
df.tail()

class cap-surface bruises odor population
8119     e           s       f    n          c
8120     e           s       f    n          v
8121     e           s       f    n          c
8122     p           y       f    y          v
8123     e           s       f    n          c

In [97]:
df['class'] = ['poisonous'if i == 'p' else 'edible' for i in df['class']]

In [7]:
# df['cap-shape'] = ['bell' if i == 'b' else i for i in df['cap-shape']]
# df['cap-shape'] = ['conical' if i == 'c' else i for i in df['cap-shape']]
# df['cap-shape'] = ['convex' if i == 'x'else i  for i in df['cap-shape']]
# df['cap-shape'] = ['flat' if i == 'f'else i  for i in df['cap-shape']]
# df['cap-shape'] = ['sunken' if i == 's' else i for i in df['cap-shape']]
# df['cap-shape'] = ['knobbed' if i == 'k' else i  for i in df['cap-shape']]

In [98]:
df.tail()

class cap-surface bruises odor population
8119     edible           s       f    n          c
8120     edible           s       f    n          v
8121     edible           s       f    n          c
8122  poisonous           y       f    y          v
8123     edible           s       f    n          c

In [99]:
df['cap-surface'] = ['fibrous' if i == 'f' else i for i in df['cap-surface']]
df['cap-surface'] = ['grooves' if i == 'g' else i for i in df['cap-surface']]
df['cap-surface'] = ['scaly' if i == 'y'else i  for i in df['cap-surface']]
df['cap-surface'] = ['smooth' if i == 's'else i  for i in df['cap-surface']]


In [100]:
df.head()

class cap-surface bruises odor population
0  poisonous      smooth       t    p          s
1     edible      smooth       t    a          n
2     edible      smooth       t    l          n
3  poisonous       scaly       t    p          s
4     edible      smooth       f    n          a

In [11]:
# df['cap-color'] = ['brown' if i == 'n' else i for i  in  df['cap-color']]
# df['cap-color'] = ['buff' if i == 'b' else i for i  in  df['cap-color']]
# df['cap-color'] = ['cinnamon' if i == 'c'   else i  for i in df['cap-color']]
# df['cap-color'] = ['gray' if i == 'g'  else i  for i in df['cap-color']]
# df['cap-color'] = ['green' if i == 'r' else i for i  in  df['cap-color']]
# df['cap-color'] = ['pink' if i == 'p' else i for i  in  df['cap-color']]
# df['cap-color'] = ['puprple' if i == 'u'   else i  for i in df['cap-color']]
# df['cap-color'] = ['red' if i == 'e'  else i  for i in df['cap-color']]
# df['cap-color'] = ['white' if i == 'w'  else i  for i in df['cap-color']]
# df['cap-color'] = ['yellow' if i == 'y'  else i  for i in df['cap-color']]

In [101]:
df.head()

class cap-surface bruises odor population
0  poisonous      smooth       t    p          s
1     edible      smooth       t    a          n
2     edible      smooth       t    l          n
3  poisonous       scaly       t    p          s
4     edible      smooth       f    n          a

In [102]:
df['bruises'] = ['bruises' if i == 't'  else i  for i in df['bruises']]
df['bruises'] = ['no' if i == 'f'  else i  for i in df['bruises']]

In [103]:
df.head()

class cap-surface  bruises odor population
0  poisonous      smooth  bruises    p          s
1     edible      smooth  bruises    a          n
2     edible      smooth  bruises    l          n
3  poisonous       scaly  bruises    p          s
4     edible      smooth       no    n          a

In [15]:
#,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s
# df['odor'] = ['almond' if i == 'a' else i for i  in  df['odor']]
# df['odor'] = ['anise' if i == 'l'   else i  for i in df['odor']]
# df['odor'] = ['creosote' if i == 'c'  else i  for i in df['odor']]
# df['odor'] = ['fishy' if i == 'y'  else i  for i in df['odor']]
# df['odor'] = ['foul' if i == 'f'  else i  for i in df['odor']]      
# df['odor'] = ['musty' if i == 'm'  else i  for i in df['odor']]
# df['odor'] = ['none' if i == 'n'  else i  for i in df['odor']]
# df['odor'] = ['pungent' if i == 'p'  else i  for i in df['odor']]   
# df['odor'] = ['spicy' if i == 's'  else i  for i in df['odor']]   

In [105]:
del df['odor']

In [106]:
df

class cap-surface  bruises population
0     poisonous      smooth  bruises          s
1        edible      smooth  bruises          n
2        edible      smooth  bruises          n
3     poisonous       scaly  bruises          s
4        edible      smooth       no          a
...         ...         ...      ...        ...
8119     edible      smooth       no          c
8120     edible      smooth       no          v
8121     edible      smooth       no          c
8122  poisonous       scaly       no          v
8123     edible      smooth       no          c

[8124 rows x 4 columns]

In [107]:
# population: abundant=a,clustered=c,numerous=n,scattered=s,several=v,solitary=y

df['population'] = ['abundant' if i == 'a' else i for i in df['population']]
df['population'] = ['clustered' if i == 'c' else i for i in df['population']]
df['population'] = ['numerous' if i == 'n'else i  for i in df['population']]
df['population'] = ['scattered' if i == 's'else i  for i in df['population']]
df['population'] = ['several' if i == 'v'else i  for i in df['population']]
df['population'] = ['solitary' if i == 'y'else i  for i in df['population']]

In [108]:
df.tail()

class cap-surface bruises population
8119     edible      smooth      no  clustered
8120     edible      smooth      no    several
8121     edible      smooth      no  clustered
8122  poisonous       scaly      no    several
8123     edible      smooth      no  clustered

In [109]:
# habitat: grasses=g,leaves=l,meadows=m,paths=p,urban=u,waste=w,woods=d

In [20]:
# df['habitat'] = ['grasses' if i == 'g' else i for i in df['habitat']]
# df['habitat'] = ['leaves' if i == 'l' else i for i in df['habitat']]
# df['habitat'] = ['meadows' if i == 'm'else i  for i in df['habitat']]
# df['habitat'] = ['paths' if i == 'p'else i  for i in df['habitat']]
# df['habitat'] = ['urban' if i == 'u'else i  for i in df['habitat']]
# df['habitat'] = ['waste' if i == 'w'else i  for i in df['habitat']]
# df['habitat'] = ['woods' if i == 'd'else i  for i in df['habitat']]

In [110]:
df.head()

class cap-surface  bruises population
0  poisonous      smooth  bruises  scattered
1     edible      smooth  bruises   numerous
2     edible      smooth  bruises   numerous
3  poisonous       scaly  bruises  scattered
4     edible      smooth       no   abundant

In [111]:

df.tail()

class cap-surface bruises population
8119     edible      smooth      no  clustered
8120     edible      smooth      no    several
8121     edible      smooth      no  clustered
8122  poisonous       scaly      no    several
8123     edible      smooth      no  clustered

In [112]:
dataset_copy = df 

In [113]:
dataset_copy

class cap-surface  bruises population
0     poisonous      smooth  bruises  scattered
1        edible      smooth  bruises   numerous
2        edible      smooth  bruises   numerous
3     poisonous       scaly  bruises  scattered
4        edible      smooth       no   abundant
...         ...         ...      ...        ...
8119     edible      smooth       no  clustered
8120     edible      smooth       no    several
8121     edible      smooth       no  clustered
8122  poisonous       scaly       no    several
8123     edible      smooth       no  clustered

[8124 rows x 4 columns]

In [114]:
dataset_copy.isna().sum()

class          0
cap-surface    0
bruises        0
population     0
dtype: int64

In [115]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import OrdinalEncoder,LabelBinarizer

In [116]:
dataset_copy.columns

Index(['class', 'cap-surface', 'bruises', 'population'], dtype='object')

In [120]:

# cap_shape = dataset_copy['cap-shape'].values.reshape(-1,1)
cap_surface= dataset_copy['cap-surface'].values.reshape(-1,1)
# cap_color = dataset_copy['cap-color'].values.reshape(-1,1)
bruises = dataset_copy['bruises'].values.reshape(-1,1)
# odor = dataset_copy['odor'].values.reshape(-1,1)
population = dataset_copy['population'].values.reshape(-1,1)
# habitat = dataset_copy['habitat'].values.reshape(-1,1)


In [121]:
cap_shape.shape, bruises.shape

((8124, 1), (8124, 1))

In [124]:
def preprocess():
    # Using ordinal encoder to convert the categories in the range from 0 to n-1
#     cap_shape_enc = OrdinalEncoder()
#     cap_shape_ = cap_shape_enc.fit_transform(cap_shape)

    cap_surface_enc = OrdinalEncoder()
    cap_surface_ = cap_surface_enc.fit_transform(cap_surface)

#     cap_color_enc = OrdinalEncoder()
#     cap_color_ = cap_color_enc.fit_transform(cap_color)
    
    bruises_enc = OrdinalEncoder()
    bruises_ = bruises_enc.fit_transform(bruises)

#     odor_enc = OrdinalEncoder()
#     odor_ = odor_enc.fit_transform(odor)

    population_enc = OrdinalEncoder()
    population_ = population_enc.fit_transform(population)
    
#     habitat_enc = OrdinalEncoder()
#     habitat_ = habitat_enc.fit_transform(habitat)


    # Stacking all the features
    X = np.column_stack((cap_surface_,bruises_,population_))
    
    
    # Changing the type to int
    X = X.astype(int)
    
    # Doing one hot encoding on the target data
    y = dataset_copy['class']
    lb = LabelBinarizer()
    y_ = lb.fit_transform(y)
    if y_.shape[1] == 1:
        y_ = np.concatenate((1 - y_, y_), axis=1)
    return X,y_,lb.classes_

In [157]:
X,y,classes = preprocess()
X.shape, y.shape

AttributeError: 'numpy.ndarray' object has no attribute 'corr'

In [127]:
masking = y[:,1].astype(bool)

In [54]:
 np.bincount(x_test[masking])

array([   0,    0,  192,  576, 2160,   36,  120,  256,  576], dtype=int64)

In [128]:
def counts_based_onclass(X,y):
    
    # No of feature
    n_features = X.shape[1]
    # No of classes
    n_classes = y.shape[1]
    
    count_matrix = []
    # For each feature
    for i in range(n_features):
        count_feature = []
        # Get that particuar feature from the dataset
        X_feature = X[:,i]
        # For each class
        for j in range(n_classes):
            # Get the datapoints that belong to the class - j
            mask = y[:,j].astype(bool)
            # Using masking filter out the datapoints that belong to this class- j in the given feature - i
            # Using bincount -- count all the different categories present in the given feature
            counts = np.bincount(X_feature[mask])
            
            count_feature.append(counts)
            
        count_matrix.append(np.array(count_feature))
        # Finding the count of datapoints beloging to each class -- we will use it to calculate prior probabilities.
        class_count = y.sum(axis=0)
        
    return count_matrix,n_features,n_classes,class_count
            

In [129]:
count_matrix,n_features,n_classes,class_count = counts_based_onclass(X,y)

In [130]:
num

array([[1266,   50,   34, 1034,   18,   58,   18,  626,  722,  402],
       [1022,  122,   14,  810,    2,   90,    2,  878,  322,  674]],
      dtype=int64)

In [131]:
# np.log(num.sum(axis=1).reshape(-1,1))
a = np.array(num, dtype=int)

In [134]:
count_matrix[2]

array([[ 384,  288,  400,  880, 1192, 1064],
       [   0,   52,    0,  368, 2848,  648]], dtype=int64)

In [135]:
def calculate_likelihood_probs(count_matrix,alpha,n_features):
    log_probabilities = []
    for i in range(n_features):
        num = count_matrix[i] + alpha
#         num = np.array(num, dtype=int)
        den = num.sum(axis=1).reshape(-1,1)
        log_probability = np.log(num) - np.log(den)
        log_probabilities.append(log_probability)
    return log_probabilities

In [136]:
def calculate_prior_probs(class_count):
    
    num = class_count
    den = class_count.sum()
    
    return np.log(num)-np.log(den)

In [137]:
prior_probs = calculate_prior_probs(class_count)

In [138]:
a = count_matrix[1]

In [139]:
a = np.array(num, dtype=int)

In [140]:
np.log(a)

array([[7.1436176 , 3.91202301, 3.52636052, 6.94119006, 2.89037176,
        4.06044301, 2.89037176, 6.43935037, 6.58202514, 5.99645209],
       [6.92951677, 4.80402104, 2.63905733, 6.69703425, 0.69314718,
        4.49980967, 0.69314718, 6.77764659, 5.77455155, 6.51323011]])

In [141]:
log_probs = calculate_likelihood_probs(count_matrix,1,n_features)

In [142]:
log_probs

[array([[-0.99261095, -8.34569287, -1.0291447 , -1.30253296],
        [-1.63921357, -6.66440902, -0.81163199, -1.02037655]]),
 array([[-0.42477142, -1.06108312],
        [-1.83558495, -0.17378232]]),
 array([[-2.39292426, -2.67974091, -2.35220617, -1.56510997, -1.26194117,
         -1.37543752],
        [-8.27435701, -4.30406509, -8.27435701, -2.36356036, -0.31963367,
         -1.79892429]])]

In [143]:
def predict(query_point,log_probs,prior_probs):
    
    # Intializing an empty array
    probs = np.zeros((1,n_classes))
    # For each feature
    for i in range(n_features):
        # Get the category_id of the feature - i from the query_point
        category = query_point[i]
        # Fetch the corresponding log_probability table and add continue to add them for all the features
        probs+=log_probs[i][:,category]
    # Finally add posterior probability
    probs+=prior_probs
    # Finding the maximum of the probabilities and fetching the corresponding class
    return classes[np.argmax(probs)]
    

In [147]:
from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()
clf.fit(X, df['class'])
print('Sklearn feature log-probabilities\n',clf.feature_log_prob_)
print('Manually implemented likelihood probabilities\n',log_probs)

print('Sklearn feature prior-probabilities\n',clf.class_log_prior_)
print('Manually implemented prior probabilities\n',prior_probs)

print()
print('Sklearn predict',clf.predict(X[4:5]))
print('Manual predict',predict(X[3],log_probs,prior_probs))

Sklearn feature log-probabilities
 [array([[-0.99261095, -8.34569287, -1.0291447 , -1.30253296],
       [-1.63921357, -6.66440902, -0.81163199, -1.02037655]]), array([[-0.42477142, -1.06108312],
       [-1.83558495, -0.17378232]]), array([[-2.39292426, -2.67974091, -2.35220617, -1.56510997, -1.26194117,
        -1.37543752],
       [-8.27435701, -4.30406509, -8.27435701, -2.36356036, -0.31963367,
        -1.79892429]])]
Manually implemented likelihood probabilities
 [array([[-0.99261095, -8.34569287, -1.0291447 , -1.30253296],
       [-1.63921357, -6.66440902, -0.81163199, -1.02037655]]), array([[-0.42477142, -1.06108312],
       [-1.83558495, -0.17378232]]), array([[-2.39292426, -2.67974091, -2.35220617, -1.56510997, -1.26194117,
        -1.37543752],
       [-8.27435701, -4.30406509, -8.27435701, -2.36356036, -0.31963367,
        -1.79892429]])]
Sklearn feature prior-probabilities
 [-0.65783517 -0.72975192]
Manually implemented prior probabilities
 [-0.65783517 -0.72975192]

Sklearn 

In [148]:
import seaborn as sns

In [155]:
df

class cap-surface  bruises population
0     poisonous      smooth  bruises  scattered
1        edible      smooth  bruises   numerous
2        edible      smooth  bruises   numerous
3     poisonous       scaly  bruises  scattered
4        edible      smooth       no   abundant
...         ...         ...      ...        ...
8119     edible      smooth       no  clustered
8120     edible      smooth       no    several
8121     edible      smooth       no  clustered
8122  poisonous       scaly       no    several
8123     edible      smooth       no  clustered

[8124 rows x 4 columns]

In [158]:
X

array([[3, 0, 3],
       [3, 0, 2],
       [3, 0, 2],
       ...,
       [3, 1, 1],
       [2, 1, 4],
       [3, 1, 1]])

In [159]:
X.shape[1]

3